include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "Pipelines/PaM-Info-Nextflow.gitlab-ci.yml"

talisman:
  variables:
    TALISMAN_OPTS: "--scan --ignoreHistory"

check_scan_results:
  variables:
    MEDIUM_LIMIT: 3
